name: Tanya Powell
title: Everything you want to know about Tanya Powell

description: "{ Software Engineer | Wannabe Chef | Photographer | Reality TV Enthuiast }"

author:
  twitter: tanya_powell

twitter:
  username: tanya_powell

# logo:

# social:
#   github: tanyapowell
#   twitter: tanya_powell
#   pinterest: tanya_powell

google_analytics: UA-69471485-1

url: http://tanyapowell.co.uk

gems:
  - jekyll-seo-tag

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
